site_name: HDX Python Database
repo_url: https://github.com/OCHA-DAP/hdx-python-database/
repo_name: OCHA-DAP/hdx-python-database
docs_dir: .
site_dir: ../site
theme:
  name: material
  highlightjs: true
plugins:
  - search
  - mkapi
nav:
  - Home: index.md
  - API Documentation:
    - Database: $src/hdx.database.*
    - PostgreSQL specific: $src/hdx.database.postgresql.*
